name: Delete All Artifacts

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete Artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            for (const artifact of artifacts.data.artifacts) {
              console.log(`Deleting artifact ${artifact.name}...`);
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id
              });
            }
