name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - runtime: win-x64
            os: win
            extension: .exe
            runs-on: ubuntu-latest
          - runtime: linux-x64
            os: linux
            extension: ''
            runs-on: ubuntu-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Extract version
      id: version
      run: |
        VERSION="${GITHUB_REF#refs/tags/}"
        VERSION="${VERSION#v}"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    - name: Build framework-dependent (non-standalone)
      run: |
        # Clean publish directory
        rm -rf ./publish-framework || true
        mkdir -p ./publish-framework
        
        dotnet publish ./RSA.CLI/RSA.CLI.csproj -c Release -r ${{ matrix.runtime }} \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          --self-contained false \
          -o ./publish-framework/
    - name: Build standalone
      run: |
        # Clean publish directory
        rm -rf ./publish-standalone || true
        mkdir -p ./publish-standalone
        
        dotnet publish ./RSA.CLI/RSA.CLI.csproj -c Release -r ${{ matrix.runtime }} \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          --self-contained true \
          -o ./publish-standalone/
    - name: Rename executables
      run: |
        # Framework-dependent executable
        if [ "${{ matrix.runtime }}" = "win-x64" ]; then
          cp "./publish-framework/RSA.CLI.exe" "csrsa-cli-${{ matrix.os }}-${{ matrix.runtime }}-${{ steps.version.outputs.VERSION }}${{ matrix.extension }}"
        else
          cp "./publish-framework/RSA.CLI" "csrsa-cli-${{ matrix.os }}-${{ matrix.runtime }}-${{ steps.version.outputs.VERSION }}${{ matrix.extension }}"
        fi
        
        # Standalone executable
        if [ "${{ matrix.runtime }}" = "win-x64" ]; then
          cp "./publish-standalone/RSA.CLI.exe" "csrsa-cli-${{ matrix.os }}-${{ matrix.runtime }}-${{ steps.version.outputs.VERSION }}-standalone${{ matrix.extension }}"
        else
          cp "./publish-standalone/RSA.CLI" "csrsa-cli-${{ matrix.os }}-${{ matrix.runtime }}-${{ steps.version.outputs.VERSION }}-standalone${{ matrix.extension }}"
        fi
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.runtime }}
        path: csrsa-cli-*
        retention-days: 1

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Extract version
      id: version
      run: |
        VERSION="${GITHUB_REF#refs/tags/}"
        VERSION="${VERSION#v}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build framework-dependent (non-standalone)
      run: |
        # Clean publish directory
        rm -rf ./publish-framework || true
        mkdir -p ./publish-framework
        
        dotnet publish ./RSA.CLI/RSA.CLI.csproj -c Release -r osx-arm64 \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          --self-contained false \
          -o ./publish-framework/

    - name: Build standalone
      run: |
        # Clean publish directory
        rm -rf ./publish-standalone || true
        mkdir -p ./publish-standalone
        
        dotnet publish ./RSA.CLI/RSA.CLI.csproj -c Release -r osx-arm64 \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          --self-contained true \
          -o ./publish-standalone/

    - name: Rename executables
      run: |
        # Framework-dependent executable
        cp "./publish-framework/RSA.CLI" "csrsa-cli-osx-silicon-$VERSION"
        
        # Standalone executable
        cp "./publish-standalone/RSA.CLI" "csrsa-cli-osx-silicon-$VERSION-standalone"
        
        # Make executables executable
        chmod +x csrsa-cli-osx-silicon-*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-osx-silicon
        path: csrsa-cli-*
        retention-days: 1
  
  release:
    needs: [build, build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: build-*
        merge-multiple: true
        path: ./

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: csrsa-cli-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
